@extends('templates.frontend.header')
@section('content')

<section>
<div class="container">
	<div class="row">
		<div class="col-lg-12  col-md-12 col-xs-12">
			<h2 style="margin-top: 100px;">Refund Policy:</h2>
	<h6 class="privacy-heading"> Billing, Termination, Cancellation and Refund on One-Month Subscriptions</h6>
	<p class="privacy-para">Grobiz offers one-month subscriptions, which entitle the original purchaser access to Grobiz for a period of exactly 1 month from the date of purchase. Grobiz also offers add-on plans for each app, which allows purchaser access to Grobiz’s additional services, including unlimited push notifications, dedicated account manager, for a period of one month. The purchaser agrees to pay all fees in effect when incurred. You will be billed for your subscription in advance at the time of purchase and the subscription will automatically renew indefinitely until explicitly cancelled. If you cancel your services, your cancellation takes effect on your next billing cycle. This means we won’t be able to refund you for early contract cancellation. All Grobiz accounts begin with an obligation-free trial which will allow you to evaluate the service. Your credit card information will be collected to initiate a trial account. However, charges will only be applied after explicit account purchase. Please sign up for a monthly payment schedule if you are unsure of how long you will be using the service. If you have a question about charges made to your account, please contact us immediately. If the charges were made in error, we will immediately credit your account or credit card account for the appropriate amount. Grobiz has a zero tolerance policy for chargebacks. Any customer who disputes a credit card payment that is found to be valid will be permanently blacklisted and barred from use of the Service. Any past due fees and costs will be sent to collections. If our collection efforts fail, unpaid debts will be reported to all available credit reporting agencies. If Grobiz terminates your account because of a violation of our terms of service, Grobiz will not refund any portion of your license fees. Refunds are not applicable on rejection of your mobile application from any App Store or marketplace. We offer a 30-day money back guarantee, hence if you cancel your subscription in this period, we will refund the entire amount to you. However, cancellation of the monthly plan after this period will not result in a refund.</p>
	<h6 class="privacy-heading"> Billing, Termination, Cancellation and Refund on One-Year Subscriptions</h6>
	<p class="privacy-para">Grobiz offers one-year subscriptions, which entitle the original purchaser access to Grobiz for a period of exactly 12 months from the date of purchase. Grobiz also offers add-on plans for each app, which allows purchaser access to Grobiz’s additional services, including unlimited push notifications, dedicated account manager, for a period of one year (12 months). The purchaser agrees to pay all fees in effect when incurred. You will be billed for your subscription in advance at the time of purchase and the subscription will automatically renew indefinitely until explicitly cancelled. If you cancel your services, your cancellation takes effect on your next billing cycle. This means we won’t be able to refund you for early contract cancellation. All Grobiz accounts begin with an obligation-free trial which will allow you to evaluate the service. Your credit card information will be collected to initiate a trial account. However, charges will only be applied after explicit account purchase. Please sign up for a monthly payment schedule if you are unsure of how long you will be using the service. If you have a question about charges made to your account, please contact us immediately. If the charges were made in error, we will immediately credit your account or credit card account for the appropriate amount. Grobiz has a zero tolerance policy for chargebacks. Any customer who disputes a credit card payment that is found to be valid will be permanently blacklisted and barred from use of the Service. Any past due fees and costs will be sent to collections. If our collection efforts fail, unpaid debts will be reported to all available credit reporting agencies. If Grobiz terminates your account because of a violation of our terms of service, Grobiz will not refund any portion of your license fees. Refunds are not applicable on rejection of your mobile application from any App Store or marketplace. We offer a 30-day money back guarantee, hence if you cancel your subscription in this period, we will refund the entire amount to you. However, cancellation of the yearly plan after this period will not result in a refund.</p>
	<h6 class="privacy-heading"> Free Trials, Cancellations, and Refund on Subscription Renewals</h6>
<p class="privacy-para">All Grobiz accounts begin with an obligation-free trial which will allow you to evaluate the service. Your credit card information will be collected to initiate a trial account. However, charges will only be applied after explicit account purchase. Please sign up for a monthly payment schedule if you are unsure of how long you will be using the service. Unfortunately, we can’t provide extensions to the free trial period and once billing has taken place, we are not able to offer refunds. If you decide to become a subscriber, you can upgrade to one of our paid plans even during the 2-day trial period. Once you have subscribed to one of our paid plans, your subscription will renew automatically, on your monthly or annual renewal date, until you cancel. Your cancellation stops all future payments only and no refunds will be offered on renewal payments made to date. Renewal rates are subject to change, but we’ll always notify you beforehand. Cancellations can be made any time by visiting the billing info page of your app or by contacting support@grobiz.app. Please note that once billing has taken place, we are not able to offer refunds. The availability and duration of the free trial may vary by region and payment gateways.</p>
<h6 class="privacy-heading"> Custom Mobile Apps Development</h6>
<p class="privacy-para">Payments for custom App design and development projects are made to us in increments as a courtesy to the client. Once a payment or deposit is made, it is non-refundable. If a project is cancelled or postponed, Grobiz retains all monies paid and if applicable, a fee for all work completed beyond what was already paid for shall be paid by the client.</p>

<h6 class="privacy-heading">  Payment for Additional Services</h6>
<p class="privacy-para">Growbiz offers additional Consumable in-app purchases that includes, but not limited to, Domain Name Registration, Premium Background Images, App Promotion (Appy Jump), App Hosting, App Bandwidth, Submission, Resubmission, Account Manager, Unlimited Push Notifications, Additional Drivers & Moderators, which you can select depending on your needs. Once a payment or deposit is made for these services, it is non-refundable. Consumable in-app purchases are depleted but can be upgraded on need basis and email notifications are sent to users when critical level thresholds are reached. It is pertinent to mention here that if Consumable in-app purchases are fully depleted and not upgraded, then this will lead to your app being locked for editing and viewing purposes.</p>
<h6 class="privacy-heading"> Content Posted on Other Services</h6>
<p class="privacy-para">We have not reviewed, and cannot review, all of the material, including computer software, made available through the services and webpages to which grobiz.app links, and that link to grobiz.app. Grobiz doesn’t have any control over those non-Grobiz services and web pages, and is not responsible for their contents or their use. By linking to a non-Grobiz website or webpage, Grobiz does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Grobiz disclaims any responsibility for any harm resulting from your use of non-Grobiz websites and web pages.</p>
	</div>
	</div>
</div>

</section>




@endsection